# Generated by Django 5.2.3 on 2025-09-27 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='performance',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='performance',
            name='reviewer',
        ),
        migrations.RemoveField(
            model_name='training',
            name='employee',
        ),
        migrations.DeleteModel(
            name='Leave',
        ),
        migrations.DeleteModel(
            name='Performance',
        ),
        migrations.DeleteModel(
            name='Training',
        ),
    ]
